"""Backup management for Homebrew packages."""

import logging
import os
import platform
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional

from .utils import run_command, BrewError


class BrewBackupManager:
    """Manages Brewfile backups with git integration."""

    def __init__(self, backup_dir: Optional[Path] = None, dry_run: bool = False):
        """
        Initialize the backup manager.

        Args:
            backup_dir: Custom backup directory (default: project_root/backups)
            dry_run: If True, don't actually execute commands
        """
        self.logger = logging.getLogger('brew_maintainer')
        self.dry_run = dry_run

        # Determine backup directory
        if backup_dir:
            self.backup_dir = Path(backup_dir)
        else:
            # Default to backups/ in project root
            project_root = Path(__file__).parent.parent
            self.backup_dir = project_root / 'backups'

        hostname = platform.node().split('.')[0].lower()
        self.brewfile_path = self.backup_dir / f'Brewfile.{hostname}'

    def create_backup(self) -> Dict[str, Any]:
        """
        Create or update the Brewfile backup.

        Returns:
            Dictionary with backup statistics

        Raises:
            BrewError: If backup creation fails
        """
        # Ensure backup directory exists
        if not self.dry_run:
            self.backup_dir.mkdir(parents=True, exist_ok=True)

        self.logger.debug(f"Creating backup at: {self.brewfile_path}")

        # Generate Brewfile. Descriptions are emitted by default; the
        # --describe switch that used to request them is deprecated.
        try:
            run_command([
                'brew', 'bundle', 'dump',
                '--file', str(self.brewfile_path),
                '--force'  # Overwrite existing
            ], dry_run=self.dry_run)

        except Exception as e:
            raise BrewError(f"Failed to create Brewfile: {e}")

        # Add timestamp header
        if not self.dry_run:
            self._add_timestamp_header()

        # Git commit if in a git repo
        self._git_commit_if_repo()

        # Count packages
        stats = {
            'formulae_count': self._count_formulae(),
            'casks_count': self._count_casks(),
            'taps_count': self._count_taps(),
            'backup_created': True
        }

        return stats

    def restore_from_backup(self) -> None:
        """
        Restore packages from Brewfile.

        Raises:
            BrewError: If restore fails or Brewfile doesn't exist
        """
        if not self.brewfile_path.exists():
            raise BrewError(
                f"Brewfile not found at {self.brewfile_path}. "
                "Create a backup first with 'backup' command."
            )

        self.logger.info(f"Restoring from: {self.brewfile_path}")

        try:
            run_command([
                'brew', 'bundle', 'install',
                '--file', str(self.brewfile_path)
            ], dry_run=self.dry_run)

        except Exception as e:
            raise BrewError(f"Failed to restore from Brewfile: {e}")

    def _add_timestamp_header(self) -> None:
        """Add a timestamp comment to the top of the Brewfile."""
        if not self.brewfile_path.exists():
            return

        try:
            # Read existing content
            with open(self.brewfile_path, 'r') as f:
                content = f.read()

            # Add timestamp header
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            header = f"# Brewfile - Updated: {timestamp}\n"
            header += "# Generated by brew-maintainer\n\n"

            # Write back with header
            with open(self.brewfile_path, 'w') as f:
                f.write(header + content)

        except Exception as e:
            self.logger.warning(f"Failed to add timestamp header: {e}")

    def _git(self, *args: str, respect_dry_run: bool = True):
        """
        Run a git command scoped to the backup directory.

        Using `git -C` keeps every git operation pointed at the repo holding
        the Brewfile, rather than whatever directory the tool was invoked from.

        Args:
            args: Arguments to pass to git
            respect_dry_run: If False, run even in dry-run mode (read-only checks)

        Returns:
            CompletedProcess object
        """
        return run_command(
            ['git', '-C', str(self.backup_dir), *args],
            check=False,
            dry_run=self.dry_run if respect_dry_run else False
        )

    def _git_commit_if_repo(self) -> None:
        """Commit backup changes if in a git repository, then sync with remote."""
        if self.dry_run:
            self.logger.info("[DRY RUN] Would commit Brewfile to git and sync with remote")
            return

        # Check if we're in a git repo
        if not self._is_git_repo():
            self.logger.debug("Not in a git repository, skipping auto-commit")
            return

        try:
            # Add the Brewfile
            self._git('add', str(self.brewfile_path))

            # Check if there are changes to commit
            status_result = self._git(
                'status', '--porcelain', str(self.brewfile_path)
            )

            if status_result.stdout.strip():
                # Commit with timestamp
                timestamp = datetime.now().isoformat()
                commit_message = f"Update Brewfile backup - {timestamp}"

                self._git('commit', '-m', commit_message)
                self.logger.info("Backup committed to git")
            else:
                self.logger.debug("No changes to commit")

            # Sync even when nothing was committed: earlier runs, or another
            # machine, may have left commits that were never pushed.
            self._git_sync_with_remote()

        except Exception as e:
            self.logger.warning(f"Failed to commit to git: {e}")

    def _git_sync_with_remote(self) -> None:
        """
        Rebase onto the remote and push.

        The pull has to happen *after* the commit, not before: `git pull
        --rebase` refuses to run with a dirty working tree, and the freshly
        dumped Brewfile is exactly that until it has been committed.

        Each machine writes its own Brewfile.<hostname>, so rebasing is
        normally conflict-free. If it isn't, the rebase is aborted and the
        commit stays local for the next run to retry.
        """
        upstream = self._git(
            'rev-parse', '--abbrev-ref', '--symbolic-full-name', '@{upstream}'
        )
        if upstream.returncode != 0:
            self.logger.debug("No upstream branch configured, skipping remote sync")
            return

        upstream_name = upstream.stdout.strip()

        pull_result = self._git('pull', '--rebase')
        if pull_result.returncode != 0:
            # Never leave the repo mid-rebase.
            self._git('rebase', '--abort')
            self.logger.warning(
                f"Could not rebase onto {upstream_name}, leaving commit local: "
                f"{pull_result.stderr.strip()}"
            )
            return

        push_result = self._git('push')
        if push_result.returncode != 0:
            self.logger.warning(
                f"Failed to push backup: {push_result.stderr.strip()}"
            )
        else:
            self.logger.info(f"Backup pushed to {upstream_name}")

    def _is_git_repo(self) -> bool:
        """Check if the backup directory is in a git repository."""
        try:
            result = self._git('rev-parse', '--git-dir', respect_dry_run=False)
            return result.returncode == 0
        except Exception:
            return False

    def _count_formulae(self) -> int:
        """Count number of formulae in Brewfile."""
        return self._count_lines_starting_with('brew ')

    def _count_casks(self) -> int:
        """Count number of casks in Brewfile."""
        return self._count_lines_starting_with('cask ')

    def _count_taps(self) -> int:
        """Count number of taps in Brewfile."""
        return self._count_lines_starting_with('tap ')

    def _count_lines_starting_with(self, prefix: str) -> int:
        """
        Count lines in Brewfile starting with a specific prefix.

        Args:
            prefix: String prefix to match (e.g., 'brew ', 'cask ')

        Returns:
            Count of matching lines
        """
        if not self.brewfile_path.exists():
            return 0

        try:
            with open(self.brewfile_path, 'r') as f:
                count = sum(1 for line in f if line.strip().startswith(prefix))
            return count
        except Exception as e:
            self.logger.warning(f"Failed to count {prefix} lines: {e}")
            return 0
